trial_name: base
tag: ''
name: video/${dataset.scene}/${trial_name}${tag}
seed: 42

dataset:
  name: video_dataset
  scene: ${basename:${dataset.video_path}}
  video_path: skvideo.datasets.bikes # or ../datasets/video_data/${dataset.scene}
  test_fraction: 0.1  # every 10th pixel used for testing and removed from training
  sampling:
    n_samples: 200000

model:
  name: siren_mlp
  in_features: 3
  out_features: 3
  hidden_features: 256
  num_hidden_layers: 4

  composition_rank: 10
  resfield_layers: []
  capacity: n_frames
  mode: lookup
  compression: vm

system:
  name: video_system
  optimizer:
    name: Adam
    args:
      lr: 0.00005 #5e-4 0.0001
  scheduler:
    name: CosineAnnealingLR
    args:
      T_max: ${trainer.max_steps}
      eta_min: ${mul:${system.optimizer.args.lr}, 0.1}

checkpoint:
  save_top_k: -1
  every_n_train_steps: 20000
  save_last: True
trainer:
  max_steps: 100000
  log_every_n_steps: 100
  num_sanity_val_steps: 0
  val_check_interval: 2500 #10000
  # limit_train_batches: 1.0
  # limit_val_batches: 2 #0.06
  enable_progress_bar: true
