trial_name: base
tag: ''
name: tsdf/${dataset.scene}/${trial_name}${tag}
seed: 42

dataset:
  val_load_time_steps: 1
  name: tsdf_dataset
  scene: ${basename:${dataset.path}}
  path: ../DATA_ROOT/DeformingThings4D/bear3EP_Agression.anime
  num_samples: 250000

model:
  name: siren_mlp
  in_features: 4
  out_features: 1
  hidden_features: 256
  num_hidden_layers: 4

  composition_rank: 10
  resfield_layers: []
  capacity: n_frames
  mode: lookup
  compression: vm
  isosurface:
    resolution: 512
system:
  name: tsdf_system
  optimizer:
    name: Adam
    args:
      lr: 0.00005 #5e-4 0.0001
  scheduler:
    name: CosineAnnealingLR
    args:
      T_max: ${trainer.max_steps}
      eta_min: ${mul:${system.optimizer.args.lr}, 0.1}

checkpoint:
  save_top_k: -1
  every_n_train_steps: 20000
  save_last: True
trainer:
  max_steps: 200000
  log_every_n_steps: 100
  num_sanity_val_steps: 0
  val_check_interval: 10000
  enable_progress_bar: true
